# Generated by Django 4.1.7 on 2023-04-15 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plot',
            name='user_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='images/items/none.jpg', upload_to='images/items'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='plot_image',
            field=models.ImageField(default='images/plots/dirt.jpg', upload_to='images/plots'),
        ),
    ]
