# Generated by Django 4.1.7 on 2023-04-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_item_user_name_plot_user_name_alter_item_item_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='/items/none.jpg', upload_to='images/items'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='plot_image',
            field=models.ImageField(default='/plots/dirt.jpg', upload_to='images/plots'),
        ),
    ]
