# Generated by Django 4.1.7 on 2023-04-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0007_alter_item_item_image_alter_plot_plot_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(default='Seeds', max_length=100),
        ),
    ]
