# Generated by Django 4.1.7 on 2023-04-16 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farm', '0008_item_item_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='user_name',
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='farm.item')),
                ('item_quantity', models.IntegerField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('farm.item',),
        ),
    ]
