# Generated by Django 4.1.7 on 2023-04-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0011_inventoryitem_rename_user_points_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='plant_type',
            field=models.CharField(default='Turnip', max_length=100),
        ),
    ]
