# Generated by Django 4.1.7 on 2023-04-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0012_item_plant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='time_planted',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plot',
            name='time_watered',
            field=models.FloatField(default=0),
        ),
    ]
