# Generated by Django 4.2 on 2023-04-23 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0014_rename_time_planted_plot_growth_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='growth_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 0, 2, 5, 789052)),
        ),
        migrations.AlterField(
            model_name='plot',
            name='water_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 0, 2, 5, 789052)),
        ),
    ]
