# Generated by Django 4.2 on 2023-04-23 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0015_alter_plot_growth_time_alter_plot_water_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='growth_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='plot',
            name='water_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
