# Generated by Django 4.2 on 2023-04-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0016_alter_plot_growth_time_alter_plot_water_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='plot_image',
            field=models.ImageField(default='/images/plots/dirt.png', upload_to='images/plots'),
        ),
    ]
